version: "3.9"

services:
  api:
    build: ./api
    ports:
      - ${API_PORT}:3000
    init: true
    restart: always
  ui:
    image: nginx:1.21.5-alpine
    ports:
      - ${UI_PORT}:80
    volumes:
      - ./ui:/usr/share/nginx/html:ro
    depends_on:
      - api
